---
title: "Project title"
subtitle: "Report"
format: html
editor: visual
execute:
  echo: true
---

**Research Question:** How does race, age, location, presence of mental illness, and other factors impact the prevalence of police shootings in the United States?

**Introduction/Data**

**Methodology**

```{r}
#| label: load-data
#| message: false
library(tidyverse)
library(tidymodels)
police_shootings <- read_csv("data/police_shootings.csv")

```

```{r}
#| label: age-prevalence

police_shootings |>
  filter(Person.Age>0) |>
  ggplot(aes(x=Person.Age, color = Person.Race)) +
  geom_bar() +
  labs(Title = "Relationship Between Victim Age and Prevalence of Police 
       Shooting", x= "Victim Age", y = "Number of Reported Shootings", 
       legend = "Race")

```

```{r}
#| label: shootings-over-time
police_shootings |>
  ggplot(aes(x=Incident.Date.Year, fill = Person.Race)) +
  geom_bar() + 
  labs(title = "P")
  
```

```{r}
#| label: mental illness-race
police_shootings |>
  ggplot(aes(x= Person.Race , fill=Incident.Location.State)) +
  geom_bar()
```

```{r}
library(usmap)
library(ggplot2)

plot_usmap(regions = "states", color = "red")
```
